import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextProvider from "./NextProvider";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import DarkMode from "./DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dracula">
      <body className={inter.className}>
        <DarkMode>
          <NextProvider>{children}</NextProvider>
        </DarkMode>
      </body>
    </html>
  );
}
